### ISSUE TITLE
Bot removes the reactions of itself

### ISSUE THREAD

**Issue by SpeckyYT** [saanuregh/discord.js-pagination#15]
I was trying this module and I found a bizzarre undocumented feature.
When clicking on the emojis of the message, the bot removes the bot's reaction instead of the user's.

**Comment by psibean** [comment]
By chance was it your own bot that sent the message which then caused the pagination embed to be sent?

The only line in the code that removes ANY reaction is this:
````
reaction.users.remove(msg.author);
````

Where msg is the message you passed into the `paginationEmbed` function, this message should be a message that one of your users sent (and thus ran a command). The only way for the bot to remove it's own reaction instead of the users reaction is if the message you passed into `paginationEmbed` was actually authored by the bot.

Edit: [my PR](https://github.com/saanuregh/discord.js-pagination/pull/17) fixes this by exposing the user who reacted in the collect event, allowing them to be removed by their id instead.

**Comment by SpeckyYT** [comment]
I ended up not using this module, so I'll close this issue
